oneup_uploader:
    resource: .
    type: uploader

sidus_file_upload.file.download:
    path:     /fileupload/{type}/download/{identifier}
    defaults: { _controller: 'Sidus\FileUploadBundle\Action\FileDownloadAction:__invoke' }
