services:
    sidus_file_upload.resource.manager:
        alias: Sidus\FileUploadBundle\Manager\ResourceManagerInterface

    sidus_file_upload.registry.filesystem:
        alias: Sidus\FileUploadBundle\Registry\FilesystemRegistry
