services:
    Sidus\FileUploadBundle\Form\Type\ResourceType:
        class: Sidus\FileUploadBundle\Form\Type\ResourceType
        public: false
        arguments:
            - '@Sidus\FileUploadBundle\Manager\ResourceManagerInterface'
            - '@Doctrine\Common\Persistence\ManagerRegistry'
        tags:
            - { name: form.type }
